<a href="https://colab.research.google.com/github/fgsantosti/analise_dados_python/blob/main/Fundos_Imobiliarios_Analise_de_Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Verificando se os FIIs estão descontados

In [ ]:
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.7/dist-packages (0.1.68)
Requirement already satisfied: requests>=2.26 in /usr/local/lib/python3.7/dist-packages (from yfinance) (2.27.0)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.19.5)
Requirement already satisfied: lxml>=4.5.1 in /usr/local/lib/python3.7/dist-packages (from yfinance) (4.7.1)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.1.5)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from yfinance) (0.0.10)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24->yfinance) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24->yfinance) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24->yfinance) (1.15.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.0.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2021.10.8)

## Pegando os dados dos FIIs do site fundsexplorer

In [ ]:
from datetime import datetime
import pandas as pd 
import yfinance as yf 
import requests 
from bs4 import BeautifulSoup 
import plotly
import openpyxl

In [ ]:
url = 'https://www.fundsexplorer.com.br/ranking'

In [ ]:
agent = {"User-Agent":"Mozilla/5.0"}
response = requests.get(url)

soup = BeautifulSoup(response.text, 'lxml')
table = soup.find_all('table')[0]
df = pd.read_html(str(table), decimal='.', thousands=',')[0]
df

    Códigodo fundo                Setor  ... VacânciaFinanceira  QuantidadeAtivos
0           APTO11              Híbrido  ...                NaN                 0
1           FIVN11            Shoppings  ...                NaN                 1
2           BZLI11  Títulos e Val. Mob.  ...                NaN                 0
3           XTED11   Lajes Corporativas  ...            100,00%                 1
4           ALMI11   Lajes Corporativas  ...                NaN                 1
..             ...                  ...  ...                ...               ...
263        CXCE11B               Outros  ...                NaN                 1
264         MFAI11              Híbrido  ...                NaN                 0
265         RBVO11               Outros  ...                NaN                 0
266         CXTL11            Logística  ...                NaN                 3
267         BBRC11               Outros  ...              2,10%                20

[268 rows x 26 columns]

Warning: Total number of columns (26) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
df.dtypes

Códigodo fundo              object
Setor                       object
Preço Atual                 object
Liquidez Diária            float64
Dividendo                   object
DividendYield               object
DY (3M)Acumulado            object
DY (6M)Acumulado            object
DY (12M)Acumulado           object
DY (3M)Média                object
DY (6M)Média                object
DY (12M)Média               object
DY Ano                      object
Variação Preço              object
Rentab.Período              object
Rentab.Acumulada            object
PatrimônioLíq.              object
VPA                         object
P/VPA                      float64
DYPatrimonial               object
VariaçãoPatrimonial         object
Rentab. Patr.no Período     object
Rentab. Patr.Acumulada      object
VacânciaFísica              object
VacânciaFinanceira          object
QuantidadeAtivos             int64
dtype: object

In [ ]:
df.to_csv('fundos_imob.csv') #salvando dados em um arquivo .csv 
df = pd.read_csv('fundos_imob.csv') #lendo arquivo .cvs
df

     Unnamed: 0 Códigodo fundo  ... VacânciaFinanceira QuantidadeAtivos
0             0         APTO11  ...                NaN                0
1             1         FIVN11  ...                NaN                1
2             2         BZLI11  ...                NaN                0
3             3         XTED11  ...            100,00%                1
4             4         ALMI11  ...                NaN                1
..          ...            ...  ...                ...              ...
263         263        CXCE11B  ...                NaN                1
264         264         MFAI11  ...                NaN                0
265         265         RBVO11  ...                NaN                0
266         266         CXTL11  ...                NaN                3
267         267         BBRC11  ...              2,10%               20

[268 rows x 27 columns]

In [ ]:
df.dtypes

Unnamed: 0                   int64
Códigodo fundo              object
Setor                       object
Preço Atual                 object
Liquidez Diária            float64
Dividendo                   object
DividendYield               object
DY (3M)Acumulado            object
DY (6M)Acumulado            object
DY (12M)Acumulado           object
DY (3M)Média                object
DY (6M)Média                object
DY (12M)Média               object
DY Ano                      object
Variação Preço              object
Rentab.Período              object
Rentab.Acumulada            object
PatrimônioLíq.              object
VPA                         object
P/VPA                      float64
DYPatrimonial               object
VariaçãoPatrimonial         object
Rentab. Patr.no Período     object
Rentab. Patr.Acumulada      object
VacânciaFísica              object
VacânciaFinanceira          object
QuantidadeAtivos             int64
dtype: object

In [ ]:
df.isnull().sum()

Unnamed: 0                   0
Códigodo fundo               0
Setor                        2
Preço Atual                  8
Liquidez Diária              8
Dividendo                    0
DividendYield                8
DY (3M)Acumulado             9
DY (6M)Acumulado             9
DY (12M)Acumulado            9
DY (3M)Média                 9
DY (6M)Média                 9
DY (12M)Média                9
DY Ano                      23
Variação Preço               9
Rentab.Período               9
Rentab.Acumulada             9
PatrimônioLíq.               0
VPA                          0
P/VPA                        8
DYPatrimonial               36
VariaçãoPatrimonial         36
Rentab. Patr.no Período     36
Rentab. Patr.Acumulada      36
VacânciaFísica             145
VacânciaFinanceira         240
QuantidadeAtivos             0
dtype: int64

In [ ]:
df

     Unnamed: 0 Códigodo fundo  ... VacânciaFinanceira QuantidadeAtivos
0             0         APTO11  ...                NaN                0
1             1         FIVN11  ...                NaN                1
2             2         BZLI11  ...                NaN                0
3             3         XTED11  ...            100,00%                1
4             4         ALMI11  ...                NaN                1
..          ...            ...  ...                ...              ...
263         263        CXCE11B  ...                NaN                1
264         264         MFAI11  ...                NaN                0
265         265         RBVO11  ...                NaN                0
266         266         CXTL11  ...                NaN                3
267         267         BBRC11  ...              2,10%               20

[268 rows x 27 columns]

## Verificando os FIIs não descontados

In [ ]:
fiis_ndescontados = df[df['P/VPA'] >= 100]
fiis_ndescontados

     Unnamed: 0 Códigodo fundo  ... VacânciaFinanceira QuantidadeAtivos
0             0         APTO11  ...                NaN                0
2             2         BZLI11  ...                NaN                0
13           13         XPHT11  ...                NaN                5
22           22         VXXV11  ...                NaN                0
24           24         CJCT11  ...                NaN                1
..          ...            ...  ...                ...              ...
207         207         HREC11  ...                NaN                0
208         208         KINP11  ...                NaN                0
220         220         RZAG11  ...                NaN                0
230         230         HABT11  ...                NaN                0
261         261         BNFS11  ...                NaN               18

[74 rows x 27 columns]

## Verificando os FIIs descontados

Estamos considerando aqui os fundos que estão com o P/VPA menor que 100 dados os dados que temos.

In [ ]:
fiis_descontados = df[df['P/VPA'] < 100]
fiis_descontados

     Unnamed: 0 Códigodo fundo  ... VacânciaFinanceira QuantidadeAtivos
1             1         FIVN11  ...                NaN                1
3             3         XTED11  ...            100,00%                1
4             4         ALMI11  ...                NaN                1
5             5         PABY11  ...                NaN                1
6             6         ORPD11  ...                NaN                0
..          ...            ...  ...                ...              ...
263         263        CXCE11B  ...                NaN                1
264         264         MFAI11  ...                NaN                0
265         265         RBVO11  ...                NaN                0
266         266         CXTL11  ...                NaN                3
267         267         BBRC11  ...              2,10%               20

[186 rows x 27 columns]

## Verificando os FIIs descontados com a Liquidez Diária de 15000 negociações diárias

In [ ]:
fiis_descontados_ld5000 = fiis_descontados[fiis_descontados['Liquidez Diária']>15000]
fiis_descontados_ld5000

     Unnamed: 0 Códigodo fundo  ... VacânciaFinanceira QuantidadeAtivos
1             1         FIVN11  ...                NaN                1
8             8         QAGR11  ...                NaN               12
42           42         BLMR11  ...                NaN                0
43           43         BRCR11  ...             15,00%               14
48           48         BCFF11  ...                NaN                0
49           49         TORD11  ...                NaN                0
65           65         RBRP11  ...              5,00%               17
77           77         RBRR11  ...                NaN                0
79           79         RBRF11  ...                NaN                0
111         111         XPML11  ...                NaN               13
127         127         PVBI11  ...                NaN                4
128         128         LVBI11  ...              0,00%               10
132         132         JSRE11  ...             11,70%                5
133         133         HGRU11  ...              0,00%               16
156         156         TGAR11  ...                NaN                0
159         159         BRCO11  ...              0,00%               10
171         171         HGRE11  ...             26,71%               21
185         185         VINO11  ...                NaN                9
186         186         VILG11  ...                NaN               16
188         188         XPCA11  ...                NaN                0
214         214         SADI11  ...                NaN                0
216         216         HSML11  ...                NaN                5
217         217         KNRI11  ...              7,87%               20
218         218         KNRI11  ...              7,69%               20
219         219         XPLG11  ...              1,20%               13
221         221         MXRF11  ...                NaN                0
240         240         VISC11  ...                NaN               15
251         251         KISU11  ...                NaN                0

[28 rows x 27 columns]

In [ ]:
#fiis_descontados_ld5000['Liquidez Diária'] 
#fiis_descontados_ld5000['P/VPA']
s=fiis_descontados_ld5000.loc[:, ['Códigodo fundo','Setor','Preço Atual','DividendYield','Liquidez Diária', 'P/VPA', 'PatrimônioLíq.']]
s.sort_values(by='PatrimônioLíq.')

    Códigodo fundo                Setor  ... P/VPA       PatrimônioLíq.
65          RBRP11               Outros  ...  89.0  R$ 1.007.350.492,52
77          RBRR11  Títulos e Val. Mob.  ...  97.0  R$ 1.052.526.047,54
79          RBRF11  Títulos e Val. Mob.  ...  89.0  R$ 1.126.170.984,40
128         LVBI11            Logística  ...  90.0  R$ 1.352.087.107,37
156         TGAR11               Outros  ...  94.0  R$ 1.440.967.369,95
216         HSML11            Shoppings  ...  85.0  R$ 1.501.075.388,34
186         VILG11            Logística  ...  87.0  R$ 1.703.601.538,03
159         BRCO11            Logística  ...  88.0  R$ 1.753.609.368,40
48          BCFF11  Títulos e Val. Mob.  ...  93.0  R$ 1.932.209.076,88
111         XPML11            Shoppings  ...  93.0  R$ 1.945.352.415,30
171         HGRE11   Lajes Corporativas  ...  81.0  R$ 1.968.340.821,76
188         XPCA11  Títulos e Val. Mob.  ...  98.0    R$ 135.385.795,52
240         VISC11            Shoppings  ...  88.0  R$ 2.058.292.486,22
133         HGRU11              Híbrido  ...  96.0  R$ 2.178.829.394,48
221         MXRF11              Híbrido  ...  98.0  R$ 2.281.190.098,57
132         JSRE11              Híbrido  ...  71.0  R$ 2.351.705.389,52
43          BRCR11              Híbrido  ...  67.0  R$ 2.828.515.163,30
219         XPLG11            Logística  ...  94.0  R$ 2.869.525.443,04
42          BLMR11  Títulos e Val. Mob.  ...  94.0    R$ 208.637.330,82
218         KNRI11              Híbrido  ...  85.0  R$ 3.797.979.053,02
217         KNRI11              Híbrido  ...  85.0  R$ 3.797.979.053,02
8           QAGR11               Outros  ...  86.0    R$ 300.963.209,86
214         SADI11  Títulos e Val. Mob.  ...  88.0    R$ 319.808.921,34
251         KISU11  Títulos e Val. Mob.  ...  94.0    R$ 379.670.432,78
49          TORD11               Outros  ...  75.0    R$ 452.519.294,27
1           FIVN11            Shoppings  ...  54.0     R$ 64.505.673,54
185         VINO11   Lajes Corporativas  ...  95.0    R$ 735.371.783,06
127         PVBI11   Lajes Corporativas  ...  92.0    R$ 998.576.404,46

[28 rows x 7 columns]

In [ ]:
fiis_descontados_ld5000.drop_duplicates() 
fiis_descontados_ld5000.count

<bound method DataFrame.count of      Unnamed: 0 Códigodo fundo  ... VacânciaFinanceira QuantidadeAtivos
1             1         FIVN11  ...                NaN                1
8             8         QAGR11  ...                NaN               12
42           42         BLMR11  ...                NaN                0
43           43         BRCR11  ...             15,00%               14
48           48         BCFF11  ...                NaN                0
49           49         TORD11  ...                NaN                0
65           65         RBRP11  ...              5,00%               17
77           77         RBRR11  ...                NaN                0
79           79         RBRF11  ...                NaN                0
111         111         XPML11  ...                NaN               13
127         127         PVBI11  ...                NaN                4
128         128         LVBI11  ...              0,00%               10
132         132         JSRE11  ...             11,70%                5
133         133         HGRU11  ...              0,00%               16
156         156         TGAR11  ...                NaN                0
159         159         BRCO11  ...              0,00%               10
171         171         HGRE11  ...             26,71%               21
185         185         VINO11  ...                NaN                9
186         186         VILG11  ...                NaN               16
188         188         XPCA11  ...                NaN                0
214         214         SADI11  ...                NaN                0
216         216         HSML11  ...                NaN                5
217         217         KNRI11  ...              7,87%               20
218         218         KNRI11  ...              7,69%               20
219         219         XPLG11  ...              1,20%               13
221         221         MXRF11  ...                NaN                0
240         240         VISC11  ...                NaN               15
251         251         KISU11  ...                NaN                0

[28 rows x 27 columns]>

In [ ]:
fiis_descontados_ld5000.to_csv('fundos_imob_filtro.csv') #salvando dados em um arquivo .csv 
#df = fiis_descontados_ld5000.read_csv('fundos_imob.csv') #lendo arquivo .cvs